# Generated by Django 4.1.2 on 2022-10-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstDjangoApp', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
